export const TasksListConst = [
  {
    id: 1,
    body: 'Таким образом консультация с широким активом играет',
    startTime: null,
    endTime: null,
    projectId: 1,
    userId: 1,
  },
  {
    id: 2,
    body: 'Таким образом консультация с широким активом играет',
    startTime: null,
    endTime: null,
    projectId: 1,
    userId: 2,
  },
  {
    id: 3,
    body: 'Таким образом консультация с широким активом играет',
    startTime: new Date().getTime() - 1281219,
    endTime: new Date().getTime(),
    projectId: 2,
    userId: 3,
  },
  {
    id: 4,
    body: 'Таким образом консультация с широким активом играет',
    startTime: new Date().getTime() - 12812192,
    endTime: new Date().getTime() - 1281219,
    projectId: 3,
    userId: 4,
  },
  {
    id: 5,
    body: 'Таким образом консультация с широким активом играет',
    startTime: new Date().getTime() - 15812192,
    endTime: new Date().getTime() - 12812192,
    projectId: 4,
    userId: 5,
  },
];
